name: Deploy to VPS

on:
  push:
    branches:
      - main  # Remplacez par la branche appropriée

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Move dist folder as .old
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /var/www/fredchess.com/
            rm -rf /var/www/fredchess.com/*

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: dist/*
          target: /var/www/fredchess.com/
